'use strict';
const $=id=>document.getElementById(id),keys=['red','blue','draws','trials','seed'],canvas=$('chart'),ctx=canvas.getContext('2d');let result=null,revision=0;
const percent=p=>(p*100).toFixed(2)+'%';
function clear(){revision++;result=null;$('csv').disabled=$('png').disabled=true;$('rows').replaceChildren();$('summary').textContent='参数已改变，请重新运行。';ctx.fillStyle='#fffef8';ctx.fillRect(0,0,1200,1000);ctx.fillStyle='#536055';ctx.font='28px sans-serif';ctx.fillText('运行实验后，这里显示理论与模拟对比。',55,100);}
function config(){const c={};for(const k of keys){if(!$(k).value.trim())throw Error('所有参数都需要填写。');c[k]=Number($(k).value);}try{return BagLab.validate(c);}catch{throw Error('请检查整数范围：两色各 0–50、总数至少 1；抽取 1–30 且不超过总数；轮数 1–10000；种子 0–4294967295。');}}
function chart(r){const c=r.config;ctx.fillStyle='#fffef8';ctx.fillRect(0,0,1200,1000);ctx.fillStyle='#26352e';ctx.font='bold 42px sans-serif';ctx.fillText('小袋子实验室 · 理论与模拟',55,65);ctx.font='20px sans-serif';ctx.fillText(`橙 ${c.red} / 蓝 ${c.blue} · 每轮 ${c.draws} 个 · ${c.trials} 轮 · 种子 ${c.seed}`,55,105);
 for(const [index,title,data,color] of [[0,'放回抽样',r.replacement,'#bc4f28'],[1,'不放回抽样',r.without,'#246f82']]){const top=170+index*375,left=90,bottom=top+250,w=1040,step=w/(c.draws+1),max=Math.max(.01,...data.probabilities,...data.counts.map(n=>n/c.trials));ctx.fillStyle='#26352e';ctx.font='bold 28px sans-serif';ctx.fillText(title,55,top-15);ctx.font='18px sans-serif';ctx.fillText('实色：理论概率    细线：模拟频率',360,top-15);for(let k=0;k<=c.draws;k++){const x=left+k*step,bw=Math.max(6,step*.6),h=data.probabilities[k]/max*205;ctx.fillStyle=color;ctx.fillRect(x,bottom-h,bw,h);ctx.strokeStyle='#26352e';ctx.lineWidth=3;const observed=data.counts[k]/c.trials/max*205;ctx.beginPath();ctx.moveTo(x,bottom-observed);ctx.lineTo(x+bw,bottom-observed);ctx.stroke();ctx.fillStyle='#26352e';ctx.font='17px sans-serif';ctx.fillText(String(k),x,bottom+25);}ctx.strokeStyle='#a7aea2';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(left,bottom);ctx.lineTo(left+w,bottom);ctx.stroke();ctx.fillStyle='#536055';ctx.font='16px sans-serif';ctx.fillText('目标球个数 →   本面板纵轴上限 '+percent(max),left,bottom+55);}
 ctx.font='18px sans-serif';ctx.fillStyle='#536055';ctx.fillText('每轮恢复原袋；两图纵轴各自缩放，请以表格数值比较。',55,940);ctx.fillText('确定性模拟，仅用于学习；不预测下一次结果。',55,973);}
function render(r){chart(r);$('summary').textContent=`${r.config.trials} 轮已完成；每轮抽 ${r.config.draws} 个。理论与实测均可在下表核对。`;$('rows').replaceChildren();for(let k=0;k<=r.config.draws;k++){const tr=document.createElement('tr');for(const text of [k,percent(r.replacement.probabilities[k]),`${r.replacement.counts[k]} / ${percent(r.replacement.counts[k]/r.config.trials)}`,percent(r.without.probabilities[k]),`${r.without.counts[k]} / ${percent(r.without.counts[k]/r.config.trials)}`]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('rows').append(tr);}$('csv').disabled=$('png').disabled=false;}
$('settings').addEventListener('input',()=>{clear();$('status').textContent='参数已修改。旧结果已清除，导出已禁用。';});
$('settings').addEventListener('submit',e=>{e.preventDefault();clear();try{result=BagLab.compare(config());render(result);$('status').textContent='实验完成。相同参数和种子可复现相同结果。';}catch(error){$('status').textContent=error.message;}});
$('reset').onclick=()=>{if(result&&!confirm('恢复演示参数并清除当前结果？'))return;[3,2,2,1000,7].forEach((n,i)=>$(keys[i]).value=n);clear();$('status').textContent='已恢复演示参数，请运行。';};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('csv').onclick=()=>{if(result)download(new Blob([BagLab.csv(result)],{type:'text/csv;charset=utf-8'}),'bag-lab-results.csv');};
$('png').onclick=()=>{if(!result)return;const token=revision;$('png').disabled=true;canvas.toBlob(blob=>{if(token!==revision)return;if(blob)download(blob,'bag-lab-comparison.png');else $('status').textContent='图片导出失败，请重试。';$('png').disabled=false;},'image/png');};clear();
