'use strict';
(function(root){
 function integer(value,min,max,name){if(!Number.isInteger(value)||value<min||value>max)throw Error(name+' must be an integer '+min+'..'+max);return value;}
 function validate(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Settings required');const red=integer(input.red,0,50,'red'),blue=integer(input.blue,0,50,'blue'),total=red+blue;if(!total)throw Error('Bag must not be empty');return {red,blue,draws:integer(input.draws,1,Math.min(total,30),'draws'),trials:integer(input.trials,1,10000,'trials'),seed:integer(input.seed,0,4294967295,'seed')};}
 function choose(n,k){if(k<0||k>n)return 0;k=Math.min(k,n-k);let result=1;for(let i=1;i<=k;i++)result=result*(n-k+i)/i;return result;}
 function distribution(input,replacement){const c=validate(input);if(typeof replacement!=='boolean')throw Error('Mode must be boolean');const n=c.red+c.blue,p=c.red/n;return Array.from({length:c.draws+1},(_,k)=>replacement?choose(c.draws,k)*p**k*(1-p)**(c.draws-k):choose(c.red,k)*choose(c.blue,c.draws-k)/choose(n,c.draws));}
 function generator(seed){let a=seed>>>0;return()=>{a=(a+0x6D2B79F5)>>>0;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
 function simulate(input,replacement){const c=validate(input);if(typeof replacement!=='boolean')throw Error('Mode must be boolean');const random=generator((c.seed^(replacement?0x52f7a01b:0x193ac473))>>>0),counts=Array(c.draws+1).fill(0);for(let trial=0;trial<c.trials;trial++){let red=c.red,total=c.red+c.blue,hit=0;for(let j=0;j<c.draws;j++){const yes=random()<red/total;if(yes)hit++;if(!replacement){total--;if(yes)red--;}}counts[hit]++;}return {replacement,counts,probabilities:distribution(c,replacement)};}
 function compare(input){const config=validate(input);return {schema:1,config,replacement:simulate(config,true),without:simulate(config,false)};}
 function csv(result){const fresh=compare(result.config);if(JSON.stringify(fresh)!==JSON.stringify(result))throw Error('Result does not match seed and settings');const lines=['mode,red,blue,draws,trials,seed,target_count,theoretical_probability,observed_count,observed_frequency'];for(const [label,r] of [['replacement',result.replacement],['without_replacement',result.without]])r.counts.forEach((count,k)=>lines.push([label,result.config.red,result.config.blue,result.config.draws,result.config.trials,result.config.seed,k,r.probabilities[k].toPrecision(15),count,(count/result.config.trials).toPrecision(15)].join(',')));return lines.join('\r\n')+'\r\n';}
 const api={validate,distribution,simulate,compare,csv};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.BagLab=Object.freeze(api);
})(globalThis);
