const assert=require('node:assert/strict'),E=require('./engine.js');
const passed=[];function test(name,fn){fn();passed.push(name);}const c={red:3,blue:2,draws:2,trials:100,seed:7};const near=(a,b)=>assert(Math.abs(a-b)<1e-11,`${a} != ${b}`);
test('Known exact distributions',()=>{E.distribution(c,true).forEach((p,k)=>near(p,[.16,.48,.36][k]));E.distribution(c,false).forEach((p,k)=>near(p,[.1,.6,.3][k]));});
test('Independent exhaustive ordered draws: all bags up to 7 balls',()=>{for(let red=0;red<=7;red++)for(let blue=0;blue<=7-red;blue++){const n=red+blue;if(!n)continue;for(let draws=1;draws<=Math.min(n,4);draws++)for(const replace of [true,false]){const counts=Array(draws+1).fill(0);let total=0;function enumerate(remaining,depth,hit){if(depth===draws){counts[hit]++;total++;return;}for(let i=0;i<remaining.length;i++)enumerate(replace?remaining:remaining.filter((_,j)=>j!==i),depth+1,hit+(remaining[i]<red?1:0));}enumerate(Array.from({length:n},(_,i)=>i),0,0);E.distribution({...c,red,blue,draws},replace).forEach((p,k)=>near(p,counts[k]/total));}}});
test('Probability mass, support and expected count over boundary grid',()=>{for(const red of [0,1,17,50])for(const blue of [0,1,23,50]){if(!(red+blue))continue;for(const draws of [1,Math.min(red+blue,30)])for(const mode of [true,false]){const p=E.distribution({...c,red,blue,draws},mode);near(p.reduce((a,b)=>a+b,0),1);near(p.reduce((a,b,k)=>a+b*k,0),draws*red/(red+blue));assert(p.every(x=>Number.isFinite(x)&&x>=0&&x<=1));}}});
test('Determinism, totals, degenerate bags and no replacement support',()=>{for(const seed of [0,1,4294967295]){const config={...c,red:4,blue:3,draws:7,trials:10000,seed};const a=E.compare(config);assert.deepEqual(a,E.compare(config));assert.equal(a.replacement.counts.reduce((x,y)=>x+y),10000);assert.equal(a.without.counts[4],10000);}for(const red of [0,5])for(const mode of [true,false])assert.equal(E.simulate({...c,red,blue:5-red,draws:5},mode).counts[red],100);});
test('Strict invalid input rejection',()=>{for(const input of [null,[],{...c,red:-1},{...c,red:51},{...c,blue:NaN},{...c,red:0,blue:0},{...c,draws:6},{...c,trials:10001},{...c,seed:-1},{...c,seed:4294967296},{...c,seed:'7'},{...c,draws:1.5}])assert.throws(()=>E.compare(input));assert.throws(()=>E.simulate(c,'yes'));});
test('Numeric CSV rows match verified result; tampering rejected',()=>{const r=E.compare(c),rows=E.csv(r).trim().split('\r\n');assert.equal(rows.length,7);assert.equal(rows[1].split(',').length,10);assert.equal(+rows[1].split(',')[8],r.replacement.counts[0]);r.without.counts[0]++;assert.throws(()=>E.csv(r));});
console.log(JSON.stringify({status:'PASS',groups:passed},null,2));
